name = "RFTools"
uuid = "481e76ae-c2a1-11e9-35e0-4d409117bccf"
authors = ["Summers, Randall J. <rsummers@ou.edu>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
